### ISSUE TITLE
Eddystone UID layout?

### ISSUE THREAD

**Issue by jnebeker** [RadiusNetworks/scanbeacon-gem#25]
I noticed the parser layout used for Eddystone UID, defined [here](https://github.com/RadiusNetworks/scanbeacon-gem/blob/master/lib/scan_beacon/beacon_parser.rb#L5) as:

```ruby
eddystone_uid: "s:0-1=feaa,m:2-2=00,p:3-3:-41,i:4-13,i:14-19;d:20-21"
```
 
has a stray semi-colon in it before the data field instead of a comma.  Here's how it's defined in the Android Beacon Library:

```java
EDDYSTONE_UID_LAYOUT = "s:0-1=feaa,m:2-2=00,p:3-3:-41,i:4-13,i:14-19";
```

Not sure it's a huge problem since the data field isn't used in the UID scheme, but I think the semi-colon throws off the parsing of the layout.

**Comment by syoder** [comment]
Good catch!  I think Google has dropped that byte from their spec (I think it was initially a reserved byte).

**Comment by jnebeker** [comment]
Looks like it's still in the github repo, not sure if that's current:

https://github.com/google/eddystone/tree/master/eddystone-uid#frame-specification

**Comment by syoder** [comment]
Oh, right.  I got it backwards - the original spec didn't have those reserved bytes at the end.  This means that the Android Beacon Library's layout is incorrect.  If you're just scanning for beacons it would work fine, but if you want to advertise you need to include those two reserved bytes in order to meet the spec for UID.

**Comment by jnebeker** [comment]
Aha, okay that makes sense
